### ISSUE TITLE
Why did you remove UpdateAsync

### ISSUE THREAD

**Issue by zanderzhg** [nahidhasanswe/AspCore-Repository#1]
hi , I am a beginner and thank you for your project. I'm using your project to learnning unitofwork
I have a question: Why did you remove UpdateAsync

**Comment by nahidhasanswe** [comment]
Hi Django
I am extremely sorry for that. I have change the updateAsync to update.
Cause there are no default async function in EF core. You can achieve this
function using only update and use saveasync for asynchronous function. I
have separate the IQueryExecutor and Unit Of Work. Cause Query execution is
break the unitofwork pattern. If you want to use UpdateAsync then use older
version.

Thanks
Nahid

**Comment by zanderzhg** [comment]
thank you very much. i learned a lot. thank you !!!
