### ISSUE TITLE
How to use Transaction

### ISSUE THREAD

**Issue by zanderzhg** [nahidhasanswe/AspCore-Repository#2]
Hi
Like this
Private readonly  iunitofwork _unitofwork

........

Private irepositiry<user> usercontext => _unitofwork.repositor<user>()
Private irepositiry<post> postcontext => _unitofwork.repository<post>();

......

Var user = new user{name=“jack”}

Usercontext.insert(user)
//how to get user.id befor _unitofwork.saveasync
Var post = new post{title=“ef core”,userid = user.id}

Await _unitofwork.saveasync

Forgive me for texting on my phone. Thank you very much

**Comment by nahidhasanswe** [comment]
Hello zanderzhg 
You are missing to insert the post into postRepository. So, you don't need userId before save. You just refer or mapping the userId into post and finally called the SaveAsnc of unit Of Work. EF automatically mapping the userId into post.

If you face any problem, then please send me a message.

Thank You

**Comment by zanderzhg** [comment]
thank you very much
